#!/bin/bash
set -o errexit -o nounset -o pipefail
function -h {
cat <<USAGE
 USAGE: mesosflexinstall (--rel <mesos-version>)?
                         (--slave-hostname <SLAVE_HOSTNAME>)?

  Install and configure Mesos with Zookeeper support.

USAGE
}; function --help { -h ;}


function main {
  options "$@"
  global os_release
  case "$os_release" in
    ubuntu/14.04)      install ;;
    *)                 err "No support for $os_release at this time." ;;
  esac
}

function globals {
  export LC_ALL=en_US.UTF-8
}; globals

# Calls a function of the same name for each needed variable.
function global {
  for arg in "$@"
  do [[ ${!arg+isset} ]] || eval "$arg="'"$('"$arg"')"'
  done
}

function options {
  while [[ ${1:+isset} ]]
  do
    case "$1" in
      --rel)            rel="$2"                 ; shift ;;
      --slave-hostname) slave_hostname="$2"      ; shift ;; # See: MESOS-825
      --*)              err "No such option: $1" ;;
    esac
    shift
  done
}

function install {
  setup_apt "trusty"
  upgrade
  install_dependencies
  install_mesos
  install_chronos
  configure_slave
  clean_up
}

function setup_apt {
  echo "deb http://repos.mesosphere.io/ubuntu/ $1 main" |
    sudo tee /etc/apt/sources.list.d/mesosphere.list
  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
}

function upgrade {
  sudo apt-get -o Acquire::Check-Valid-Until=false update
  apt_ upgrade
}

function install_dependencies {
  apt_ install curl unzip
}

function install_mesos {
  apt_ install zookeeperd zookeeper zookeeper-bin docker.io mesos marathon
  sudo ln -sf /usr/bin/docker.io /usr/local/bin/docker
  sudo sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io
  sudo restart mesos-master || sudo start mesos-master
  sudo restart mesos-slave || sudo start mesos-slave
}

function install_chronos {
  apt_ install chronos
  sudo sh -c 'echo 8081 > /etc/chronos/conf/http_port'
  sudo restart chronos || sudo start chronos
}

function configure_slave {
  if [[ ${slave_hostname+isset} ]]
  then
    mkdir -p /etc/mesos-slave
    echo "$slave_hostname" > /etc/mesos-slave/hostname
  fi
  sudo sh -c 'echo "docker,mesos" > /etc/mesos-slave/containerizers'
}

function clean_up {
  sudo apt-get autoremove -y
}

function apt_ {
  sudo env DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold --no-install-recommends --no-install-suggests "$@"
  if [[ "$1" = "install" ]]
  then
    sudo apt-get clean -y `echo "$@" | cut -d " " -f2-`
  fi
}

function os_release {
  msg "Trying /etc/os-release..."
  if [[ -f /etc/os-release ]]
  then
    ( source /etc/os-release && display_version "$ID" "$VERSION_ID" )
    return 0
  fi
  msg "Trying /etc/redhat-release..."
  if [[ -f /etc/redhat-release ]]
  then
    # Seems to be formatted as: <distro> release <version> (<remark>)
    #                           CentOS release 6.3 (Final)
    if [[ $(cat /etc/redhat-release) =~ \
          ^(.+)' '+release' '+([^ ]+)' '+'('[^')']+')'$ ]]
    then
      local os
      case "${BASH_REMATCH[1]}" in
        'Red Hat '*) os=RedHat ;;
        *)           os="${BASH_REMATCH[1]}" ;;
      esac
      display_version "$os" "${BASH_REMATCH[2]}"
      return 0
    else
      err "/etc/redhat-release not like: <distro> release <version> (<remark>)"
    fi
  fi
  if which sw_vers &> /dev/null
  then
    local product="$(sw_vers -productName)"
    case "$product" in
      'Mac OS X') display_version MacOSX "$(sw_vers -productVersion)" ;;
      *) err "Expecting productName to be 'Mac OS X', not '$product'!";;
    esac
    return 0
  fi
  err "Could not determine OS version!"
}

function display_version {
  local os="$( tr A-Z a-z <<<"$1" )" version="$( tr A-Z a-z <<<"$2" )"
  case "$os" in
    redhat|centos|debian) out "$os/${version%%.*}" ;;   # Ignore minor versions
    macosx)               out "$os/${version%.*}" ;;  # Ignore bug fix releases
    *)                    out "$os/$version" ;;
  esac
}

function msg { out "$*" >&2 ;}
function err { local x=$? ; msg "$*" ; return $(( $x == 0 ? 1 : $x )) ;}
function out { printf '%s\n' "$*" ;}

if [[ ${1:-} ]] && declare -F | cut -d' ' -f3 | fgrep -qx -- "${1:-}"
then "$@"
else main "$@"
fi

